


class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  # extends ...................................................................
  
  # includes ..................................................................
  audited
  acts_as_paranoid

  include Searchrable

  # security (i.e. attr_accessible) ...........................................
      
  # enuns
  enum permissao: { admin: "admin" }
      
  # relationships .............................................................
  
  # validations ...............................................................
  validate_enum_attribute :permissao
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
    